name: Code Quality

on:
  push:
    branches: [ main, develop ]
  pull_request:
    branches: [ main, develop ]

jobs:
  backend-quality:
    runs-on: ubuntu-latest
    
    steps:
    - name: Checkout code
      uses: actions/checkout@v4

    - name: Set up Python
      uses: actions/setup-python@v5
      with:
        python-version: '3.11'

    - name: Install dependencies
      working-directory: ./DreamTracerBackend
      run: |
        python -m pip install --upgrade pip
        pip install -r requirements.txt
        pip install black isort flake8 mypy bandit safety

    - name: Run Black formatter check
      working-directory: ./DreamTracerBackend
      run: black --check app/

    - name: Run isort import sorting check
      working-directory: ./DreamTracerBackend
      run: isort --check-only app/

    - name: Run flake8 linter
      working-directory: ./DreamTracerBackend
      run: flake8 app/ --max-line-length=88 --extend-ignore=E203,W503

    - name: Run mypy type checker
      working-directory: ./DreamTracerBackend
      run: mypy app/ --ignore-missing-imports

    - name: Run bandit security linter
      working-directory: ./DreamTracerBackend
      run: bandit -r app/ -f json -o bandit-report.json || true

    - name: Run safety dependency check
      working-directory: ./DreamTracerBackend
      run: safety check --json --output safety-report.json || true

    - name: Upload security reports
      uses: actions/upload-artifact@v4
      with:
        name: backend-security-reports
        path: |
          DreamTracerBackend/bandit-report.json
          DreamTracerBackend/safety-report.json

  frontend-quality:
    runs-on: ubuntu-latest
    
    steps:
    - name: Checkout code
      uses: actions/checkout@v4

    - name: Set up Node.js
      uses: actions/setup-node@v4
      with:
        node-version: '18'
        cache: 'npm'
        cache-dependency-path: DreamTracerApp/package-lock.json

    - name: Install dependencies
      working-directory: ./DreamTracerApp
      run: npm ci

    - name: Run ESLint
      working-directory: ./DreamTracerApp
      run: npx eslint . --ext .ts,.tsx --max-warnings 0

    - name: Run Prettier check
      working-directory: ./DreamTracerApp
      run: npx prettier --check "src/**/*.{ts,tsx,js,jsx,json}"

    - name: Run TypeScript type check
      working-directory: ./DreamTracerApp
      run: npx tsc --noEmit

    - name: Run dependency audit
      working-directory: ./DreamTracerApp
      run: npm audit --audit-level=moderate

  dependency-review:
    runs-on: ubuntu-latest
    if: github.event_name == 'pull_request'
    
    steps:
    - name: Checkout code
      uses: actions/checkout@v4

    - name: Dependency Review
      uses: actions/dependency-review-action@v4
      with:
        fail-on-severity: moderate
        allow-licenses: MIT, Apache-2.0, BSD-2-Clause, BSD-3-Clause, ISC

  code-scanning:
    runs-on: ubuntu-latest
    
    steps:
    - name: Checkout code
      uses: actions/checkout@v4

    - name: Initialize CodeQL
      uses: github/codeql-action/init@v3
      with:
        languages: javascript, python

    - name: Autobuild
      uses: github/codeql-action/autobuild@v3

    - name: Perform CodeQL Analysis
      uses: github/codeql-action/analyze@v3
